# sections/helpers/note_calcul/constantes.py

## Météo
DJ_REF_ANNUELS = 3260.539010836340
DJ_TEMPERATURE_REFERENCE = 20

# Agents énergétiques conversion
CONVERSION_MAZOUT_MJ_KG = 44.8
CONVERSION_MAZOUT_MJ_LITRES = 44.8 * 0.84
CONVERSION_MAZOUT_MJ_KWH = 3.6
CONVERSION_GAZ_NATUREL_MJ_M3 = 38.5
CONVERSION_GAZ_NATUREL_MJ_KWH = 3.6
CONVERSION_BOIS_BUCHES_DUR_MJ_STERE = 7960
CONVERSION_BOIS_BUCHES_TENDRE_MJ_STERE = 5572
CONVERSION_BOIS_BUCHES_TENDRE_MJ_KWH = 3.6
CONVERSION_PELLETS_MJ_M3 = 13332
CONVERSION_PELLETS_MJ_KG = 20.2
CONVERSION_PELLETS_MJ_KWH = 3.6
CONVERSION_PLAQUETTES_MJ_M3 = 200 * 20
CONVERSION_PLAQUETTES_MJ_KWH = 3.6 * 13.1 / 11.6
CONVERSION_CAD_MJ_KWH = 3.6
CONVERSION_ELECTRICITE_PAC_MJ_KWH = 3.6
CONVERSION_ELECTRICITE_DIRECTE_MJ_KWH = 3.6
CONVERSION_AUTRE_MJ_KWH = 3.6

# Agent énergétique facteur de pondération
FACTEUR_PONDERATION_MAZOUT = 1
FACTEUR_PONDERATION_GAZ_NATUREL = 1
FACTEUR_PONDERATION_BOIS_BUCHES_DUR = 1
FACTEUR_PONDERATION_BOIS_BUCHES_TENDRE = 1
FACTEUR_PONDERATION_PELLETS = 1
FACTEUR_PONDERATION_PLAQUETTES = 1
FACTEUR_PONDERATION_CAD = 1
FACTEUR_PONDERATION_ELECTRICITE_PAC = 2
FACTEUR_PONDERATION_ELECTRICITE_DIRECTE = 1
FACTEUR_PONDERATION_AUTRE = 1

# --------------------------------------------
# IDC

# Agents énergétiques conversion
IDC_CONVERSION_MAZOUT_MJ_KG = 44.8
IDC_CONVERSION_MAZOUT_MJ_LITRES = 44.8 * 0.84
IDC_CONVERSION_MAZOUT_MJ_KWH = 3.6
IDC_CONVERSION_GAZ_NATUREL_MJ_M3 = 38.5
IDC_CONVERSION_GAZ_NATUREL_MJ_KWH = 3.6
IDC_CONVERSION_BOIS_BUCHES_DUR_MJ_STERE = 400*19.9
IDC_CONVERSION_BOIS_BUCHES_TENDRE_MJ_STERE = 280*19.9
IDC_CONVERSION_BOIS_BUCHES_TENDRE_MJ_KWH = 3.6
IDC_CONVERSION_PELLETS_MJ_M3 = 660*20.2
IDC_CONVERSION_PELLETS_MJ_KG = 20.2
IDC_CONVERSION_PELLETS_MJ_KWH = 3.6
IDC_CONVERSION_PLAQUETTES_MJ_M3 = 200 * 20
IDC_CONVERSION_PLAQUETTES_MJ_KWH = 3.6 * 13.1 / 11.6
IDC_CONVERSION_CAD_TARIFE_MJ_KWH = 3.892
IDC_CONVERSION_CAD_REPARTI_MJ_KWH = 3.6
IDC_CONVERSION_ELECTRICITE_PAC_AVANT_MJ_KWH = 3.6
IDC_CONVERSION_ELECTRICITE_PAC_APRES_MJ_KWH = 3.6
IDC_CONVERSION_ELECTRICITE_DIRECTE_MJ_KWH = 3.6
IDC_CONVERSION_AUTRE_MJ_KWH = 3.6

# Agent énergétique facteur de pondération
IDC_FACTEUR_PONDERATION_MAZOUT = 1
IDC_FACTEUR_PONDERATION_GAZ_NATUREL = 1
IDC_FACTEUR_PONDERATION_BOIS_BUCHES_DUR = 1
IDC_FACTEUR_PONDERATION_BOIS_BUCHES_TENDRE = 1
IDC_FACTEUR_PONDERATION_PELLETS = 1
IDC_FACTEUR_PONDERATION_PLAQUETTES = 1
IDC_FACTEUR_PONDERATION_CAD = 1 # Pertes réseau dans IDC_CONVERSION_CAD_TARIFE_MJ_KWH
IDC_FACTEUR_PONDERATION_ELECTRICITE_PAC_AVANT = 2.5
IDC_FACTEUR_PONDERATION_ELECTRICITE_PAC_APRES = 3.25
IDC_FACTEUR_PONDERATION_ELECTRICITE_DIRECTE = 1
IDC_FACTEUR_PONDERATION_AUTRE = 1

# Besoins d'énergie pour ECS
IDC_EWW_HABITAT_COLLECTIF_MJ_M2 = 128
IDC_EWW_HABITAT_INDIVIDUEL_MJ_M2 = 85
IDC_EWW_ADMINISTRATION_MJ_M2 = 43
IDC_EWW_ECOLES_MJ_M2 = 43
IDC_EWW_COMMERCE_MJ_M2 = 43
IDC_EWW_RESTAURATION_MJ_M2 = 342
IDC_EWW_LIEUX_DE_RASSEMBLEMENT_MJ_M2 = 86
IDC_EWW_HOPITAUX_MJ_M2 = 171
IDC_EWW_INDUSTRIE_MJ_M2 = 43
IDC_EWW_DEPOTS_MJ_M2 = 9
IDC_EWW_INSTALLATIONS_SPORTIVES_MJ_M2 = 513
IDC_EWW_PISCINES_COUVERTES_MJ_M2 = 513
