# sections/helpers/note_calcul/constantes.py

## Météo
DJ_REF_ANNUELS = 3260.539010836340
DJ_TEMPERATURE_REFERENCE = 20

# Agents énergétiques conversion
CONVERSION_MAZOUT_MJ_KG = 44.8
CONVERSION_MAZOUT_MJ_LITRES = 44.8 * 0.84
CONVERSION_MAZOUT_MJ_KWH = 3.6
CONVERSION_GAZ_NATUREL_MJ_M3 = 38.5
CONVERSION_GAZ_NATUREL_MJ_KWH = 3.6
CONVERSION_BOIS_BUCHES_DUR_MJ_STERE = 7960
CONVERSION_BOIS_BUCHES_TENDRE_MJ_STERE = 5572
CONVERSION_BOIS_BUCHES_TENDRE_MJ_KWH = 3.6
CONVERSION_PELLETS_MJ_M3 = 13332
CONVERSION_PELLETS_MJ_KG = 20.2
CONVERSION_PELLETS_MJ_KWH = 3.6
CONVERSION_PLAQUETTES_MJ_M3 = 200 * 20
CONVERSION_PLAQUETTES_MJ_KWH = 3.6 * 13.1 / 11.6
CONVERSION_CAD_MJ_KWH = 3.6
CONVERSION_ELECTRICITE_PAC_MJ_KWH = 3.6
CONVERSION_ELECTRICITE_DIRECTE_MJ_KWH = 3.6
CONVERSION_AUTRE_MJ_KWH = 3.6

# Agent énergétique facteur de pondération
FACTEUR_PONDERATION_MAZOUT = 1
FACTEUR_PONDERATION_GAZ_NATUREL = 1
FACTEUR_PONDERATION_BOIS_BUCHES_DUR = 1
FACTEUR_PONDERATION_BOIS_BUCHES_TENDRE = 1
FACTEUR_PONDERATION_PELLETS = 1
FACTEUR_PONDERATION_PLAQUETTES = 1
FACTEUR_PONDERATION_CAD = 1
FACTEUR_PONDERATION_ELECTRICITE_PAC = 2
FACTEUR_PONDERATION_ELECTRICITE_DIRECTE = 1
FACTEUR_PONDERATION_AUTRE = 1
