# sections/helpers/note_calcul/create_dataframe_agent_energetique.py

import pandas as pd


def make_dataframe_df_agent_energetique(
    data_site,
    FACTEUR_PONDERATION_MAZOUT,
    FACTEUR_PONDERATION_GAZ_NATUREL,
    FACTEUR_PONDERATION_BOIS_BUCHES_DUR,
    FACTEUR_PONDERATION_BOIS_BUCHES_TENDRE,
    FACTEUR_PONDERATION_PELLETS,
    FACTEUR_PONDERATION_PLAQUETTES,
    FACTEUR_PONDERATION_CAD,
    FACTEUR_PONDERATION_ELECTRICITE_PAC,
    FACTEUR_PONDERATION_ELECTRICITE_DIRECTE,
    FACTEUR_PONDERATION_AUTRE,
):
    df_agent_energetique = pd.DataFrame(
        {
            "Agent énergétique": [
                "Mazout",
                "Gaz naturel",
                "Bois (buches dur)",
                "Bois (buches tendre)",
                "Pellets",
                "Plaquettes",
                "CAD",
                "Electricité (PAC)",
                "Electricité (directe)",
                "Autre",
            ],
            "Somme MJ": [
                data_site["agent_energetique_ef_mazout_somme_mj"],
                data_site["agent_energetique_ef_gaz_naturel_somme_mj"],
                data_site["agent_energetique_ef_bois_buches_dur_somme_mj"],
                data_site["agent_energetique_ef_bois_buches_tendre_somme_mj"],
                data_site["agent_energetique_ef_pellets_somme_mj"],
                data_site["agent_energetique_ef_plaquettes_somme_mj"],
                data_site["agent_energetique_ef_cad_somme_mj"],
                data_site["agent_energetique_ef_electricite_pac_somme_mj"],
                data_site["agent_energetique_ef_electricite_directe_somme_mj"],
                data_site["agent_energetique_ef_autre_somme_mj"],
            ],
            "Somme kWh": [
                data_site["agent_energetique_ef_mazout_somme_mj"] / 3.6,
                data_site["agent_energetique_ef_gaz_naturel_somme_mj"] / 3.6,
                data_site["agent_energetique_ef_bois_buches_dur_somme_mj"] / 3.6,
                data_site["agent_energetique_ef_bois_buches_tendre_somme_mj"] / 3.6,
                data_site["agent_energetique_ef_pellets_somme_mj"] / 3.6,
                data_site["agent_energetique_ef_plaquettes_somme_mj"] / 3.6,
                data_site["agent_energetique_ef_cad_somme_mj"] / 3.6,
                data_site["agent_energetique_ef_electricite_pac_somme_mj"] / 3.6,
                data_site["agent_energetique_ef_electricite_directe_somme_mj"] / 3.6,
                data_site["agent_energetique_ef_autre_somme_mj"] / 3.6,
            ],
            "Facteur de pondération": [
                FACTEUR_PONDERATION_MAZOUT,
                FACTEUR_PONDERATION_GAZ_NATUREL,
                FACTEUR_PONDERATION_BOIS_BUCHES_DUR,
                FACTEUR_PONDERATION_BOIS_BUCHES_TENDRE,
                FACTEUR_PONDERATION_PELLETS,
                FACTEUR_PONDERATION_PLAQUETTES,
                FACTEUR_PONDERATION_CAD,
                FACTEUR_PONDERATION_ELECTRICITE_PAC,
                FACTEUR_PONDERATION_ELECTRICITE_DIRECTE,
                FACTEUR_PONDERATION_AUTRE,
            ],
            "Variable Agent énergétique": [
                "agent_energetique_ef_mazout_somme_mj",
                "agent_energetique_ef_gaz_naturel_somme_mj",
                "agent_energetique_ef_bois_buches_dur_somme_mj",
                "agent_energetique_ef_bois_buches_tendre_somme_mj",
                "agent_energetique_ef_pellets_somme_mj",
                "agent_energetique_ef_plaquettes_somme_mj",
                "agent_energetique_ef_cad_somme_mj",
                "agent_energetique_ef_electricite_pac_somme_mj",
                "agent_energetique_ef_electricite_directe_somme_mj",
                "agent_energetique_ef_autre_somme_mj",
            ],
            "Variable facteur de pondération": [
                "FACTEUR_PONDERATION_MAZOUT",
                "FACTEUR_PONDERATION_GAZ_NATUREL",
                "FACTEUR_PONDERATION_BOIS_BUCHES_DUR",
                "FACTEUR_PONDERATION_BOIS_BUCHES_TENDRE",
                "FACTEUR_PONDERATION_PELLETS",
                "FACTEUR_PONDERATION_PLAQUETTES",
                "FACTEUR_PONDERATION_CAD",
                "FACTEUR_PONDERATION_ELECTRICITE_PAC",
                "FACTEUR_PONDERATION_ELECTRICITE_DIRECTE",
                "FACTEUR_PONDERATION_AUTRE",
            ],
        }
    )
    return df_agent_energetique
